### ISSUE TITLE
Verbosity of libwint

### ISSUE THREAD

**Issue by guacke** [GQCG/libwint#12]
When using libint bases, this always gets reported to std::cout. E.g. 

Will read basis set from /user/home/gent/vsc405/vsc40558/consult/laurent_lemmens/gqcg/share/libint/2.4.2/basis/sto-3g.g94
Will read basis set from /user/home/gent/vsc405/vsc40558/consult/laurent_lemmens/gqcg/share/libint/2.4.2/basis/sto-3g.g94
Will read basis set from /user/home/gent/vsc405/vsc40558/consult/laurent_lemmens/gqcg/share/libint/2.4.2/basis/sto-3g.g94
Will read basis set from /user/home/gent/vsc405/vsc40558/consult/laurent_lemmens/gqcg/share/libint/2.4.2/basis/sto-3g.g94

Can we disable this output (either completely, or by passing a flag to libwint invocations)?

**Comment by lelemmen** [comment]
This was fixed in #13.
